# Generated by Django 4.1.1 on 2022-09-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='spacex',
            new_name='mission_name',
        ),
    ]
