# Generated by Django 4.1.1 on 2022-09-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_spacex_info_mission_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='mission_name',
            new_name='name',
        ),
    ]
