# Generated by Django 4.1.1 on 2022-09-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_mission_name_info_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='name',
            new_name='mission_name',
        ),
    ]
