# Generated by Django 4.1.1 on 2022-09-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_info_manufacturers_info_mission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='count',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
