# Generated by Django 4.1.1 on 2022-09-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_info_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='count',
        ),
    ]
