# Generated by Django 4.1.1 on 2022-09-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_info_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
